import type { AgentId } from "../lib/agent-id";
import type { CommandPaletteState } from "./useCommandPalette";
import type { ReviewController } from "./useReviewController";
import type { SlashCommands } from "./useSlashCommands";
import type { useAcpSession } from "./useAcpSession";
import type { useAppModelState } from "./useAppModelState";
import type { useAppModelView } from "./useAppModelView";
import type { useAppWorkspace } from "./useAppWorkspace";
import type { useDreamJob } from "./useDreamJob";
import type { useGitActions } from "./useGitActions";
import type { useGitWatcher } from "./useGitWatcher";
import type { useToast } from "./useToast";
import type { WebuiState, SessionSummary } from "../api";
import type { QueuedPermission } from "../lib/permission-queue";

export type PackAppModelInput = {
  s: ReturnType<typeof useAppModelState>;
  ws: ReturnType<typeof useAppWorkspace>;
  view: ReturnType<typeof useAppModelView>;
  acp: ReturnType<typeof useAcpSession>;
  dream: ReturnType<typeof useDreamJob>;
  review: ReviewController;
  palette: CommandPaletteState;
  git: ReturnType<typeof useGitWatcher>;
  gitActions: ReturnType<typeof useGitActions>;
  toast: ReturnType<typeof useToast>;
  slash: SlashCommands;
  persist: (partial: WebuiState) => void;
  reviewCwd: string;
  allSessions: SessionSummary[];
  answerPermission: (req: QueuedPermission, optionId: string) => Promise<void>;
  refreshInspect: (dir?: string) => Promise<void>;
  openHub: (tab?: "skills" | "mcp" | "marketplace" | "hooks") => void;
  openReview: (action: Parameters<ReviewController["openReview"]>[0]) => void;
  rewindForItem: (itemId: string) => (() => void) | undefined;
  dismissRecap: () => void;
  setSelectedAgentId: (id: AgentId) => void;
};

export function packAppModel(p: PackAppModelInput) {
  const { s, ws, view, acp, dream, review, palette, git, gitActions, toast, slash } = p;
  return {
    theme: s.theme,
    setTheme: s.setTheme,
    settingsOpen: s.settingsOpen,
    setSettingsOpen: s.setSettingsOpen,
    hubOpen: s.hubOpen,
    setHubOpen: s.setHubOpen,
    hubTab: s.hubTab,
    setHubTab: s.setHubTab,
    locale: s.locale,
    setLocale: s.setLocale,
    themeFamily: s.themeFamily,
    setThemeFamily: s.setThemeFamily,
    accentId: s.accentId,
    setAccentId: s.setAccentId,
    density: s.density,
    setDensity: s.setDensity,
    hideToTray: s.hideToTray,
    setHideToTray: s.setHideToTray,
    defaultRail: s.defaultRail,
    setDefaultRail: s.setDefaultRail,
    shortcuts: s.shortcuts,
    setShortcuts: s.setShortcuts,
    inspect: s.inspect,
    skillCommands: view.skillCommands,
    modelCatalog: view.modelCatalog,
    effortOptions: view.effortOptions,
    modelLabels: view.modelLabels,
    effortReady: s.effortReady,
    extraPage: s.extraPage,
    setExtraPage: s.setExtraPage,
    imagineImages: s.imagineImages,
    imagineVideos: s.imagineVideos,
    agentRows: s.agentRows,
    managed: s.managed,
    usageHistory: s.usageHistory,
    appConfirm: s.appConfirm,
    confirmAppModal: () => {
      const pending = s.appConfirm;
      s.setAppConfirm(null);
      ws.confirmAppModal(pending);
    },
    cancelAppModal: () => s.setAppConfirm(null),
    usageDays: s.usageDays,
    setUsageDays: s.setUsageDays,
    jumpTurnId: s.jumpTurnId,
    doctorNote: s.doctorNote,
    setDoctorNote: s.setDoctorNote,
    threadView: s.threadView,
    setThreadView: s.setThreadView,
    sidebarCollapsed: s.sidebarCollapsed,
    setSidebarCollapsed: s.setSidebarCollapsed,
    millerOpen: s.millerOpen,
    setMillerOpen: s.setMillerOpen,
    jobsOpen: s.jobsOpen,
    setJobsOpen: s.setJobsOpen,
    catalogOpen: s.catalogOpen,
    setCatalogOpen: s.setCatalogOpen,
    searchJump: s.searchJump,
    setSearchJump: s.setSearchJump,
    chatFontSize: s.chatFontSize,
    setChatFontSize: s.setChatFontSize,
    cwd: s.cwd,
    reviewCwd: p.reviewCwd,
    reviewPlan: view.reviewPlan,
    setCwd: s.setCwd,
    projects: s.projects,
    openProjects: s.openProjects,
    setOpenProjects: s.setOpenProjects,
    sessions: s.sessions,
    draft: s.draft,
    weeklyUsage: s.weeklyUsage,
    mode: s.mode,
    setMode: s.setMode,
    model: s.model,
    setModel: s.setModel,
    showThinking: s.showThinking,
    setShowThinking: s.setShowThinking,
    chatWidth: s.chatWidth,
    setChatWidth: s.setChatWidth,
    info: s.info,
    setInfo: s.setInfo,
    cli: s.cli,
    setCli: s.setCli,
    toast: toast.toast,
    pauseToast: toast.pauseToast,
    resumeToast: toast.resumeToast,
    atBottom: s.atBottom,
    setAtBottom: s.setAtBottom,
    paneTree: s.paneTree,
    focusedPaneId: s.focusedPaneId,
    extraPanes: s.extraPanes,
    paneDrag: s.paneDrag,
    paneCount: view.paneCount,
    openIds: view.openIds,
    focusedSessionId: view.focusedSessionId,
    workColRef: s.workColRef,
    extraChatEls: s.extraChatEls,
    extraComposerRefs: s.extraComposerRefs,
    extraMentionData: s.extraMentionData,
    extraBusyStartRef: s.extraBusyStartRef,
    clock: s.clock,
    picking: s.picking,
    titles: s.titles,
    editingTitleId: s.editingTitleId,
    titleDraft: s.titleDraft,
    setTitleDraft: s.setTitleDraft,
    menu: s.menu,
    setMenu: s.setMenu,
    inboxCwd: s.inboxCwd,
    setInboxCwd: s.setInboxCwd,
    inboxSessions: s.inboxSessions,
    movePick: s.movePick,
    setMovePick: s.setMovePick,
    pinned: s.pinned,
    setPinned: s.setPinned,
    archived: s.archived,
    setArchived: s.setArchived,
    enterSends: s.enterSends,
    setEnterSends: s.setEnterSends,
    autoArchiveDays: s.autoArchiveDays,
    setAutoArchiveDays: s.setAutoArchiveDays,
    lastWorkspace: s.lastWorkspace,
    setLastWorkspace: s.setLastWorkspace,
    sidebarList: s.sidebarList,
    setSidebarList: s.setSidebarList,
    pinnedProjects: s.pinnedProjects,
    setPinnedProjects: s.setPinnedProjects,
    projectGroups: s.projectGroups,
    openGroups: s.openGroups,
    setOpenGroups: s.setOpenGroups,
    createNamedGroup: ws.createNamedGroup,
    createGroupForProject: ws.createGroupForProject,
    moveProjectToGroup: ws.moveProjectToGroup,
    renameNamedGroup: ws.renameNamedGroup,
    requestDeleteGroup: ws.requestDeleteGroup,
    sessionTokens: s.sessionTokens,
    settingsFocus: s.settingsFocus,
    setSettingsFocus: s.setSettingsFocus,
    expandedIds: s.expandedIds,
    collapsedIds: s.collapsedIds,
    setCollapsedIds: s.setCollapsedIds,
    setAllowedTools: s.setAllowedTools,
    workspaceEntries: s.workspaceEntries,
    memoryChanges: s.memoryChanges,
    setMemoryChanges: s.setMemoryChanges,
    memoryBaseline: s.memoryBaseline,
    searchHits: s.searchHits,
    setSearchHits: s.setSearchHits,
    mruOpen: s.mruOpen,
    setMruOpen: s.setMruOpen,
    rewindTarget: s.rewindTarget,
    setRewindTarget: s.setRewindTarget,
    worktreeBusy: s.worktreeBusy,
    gitBusy: gitActions.gitBusy,
    pullGit: gitActions.pullGit,
    pushGit: gitActions.pushGit,
    discardChange: gitActions.discardChange,
    queue: s.queue,
    setQueue: s.setQueue,
    steerByDefault: s.steerByDefault,
    setSteerByDefault: s.setSteerByDefault,
    injectUserMemory: s.injectUserMemory,
    setInjectUserMemory: s.setInjectUserMemory,
    dreamingEnabled: s.dreamingEnabled,
    setDreamingEnabled: s.setDreamingEnabled,
    dreamAgentId: s.dreamAgentId,
    setDreamAgentId: s.setDreamAgentId,
    doctors: s.doctors,
    unread: s.unread,
    setUnread: s.setUnread,
    sidebarWidth: s.sidebarWidth,
    setSidebarWidth: s.setSidebarWidth,
    previewWidth: s.previewWidth,
    setPreviewWidth: s.setPreviewWidth,
    winWidth: s.winWidth,
    chatEl: s.chatEl,
    composerRef: s.composerRef,
    focusedPermissionPaneRef: s.focusedPermissionPaneRef,
    titleInputRef: s.titleInputRef,
    showToast: toast.showToast,
    sessionId: acp.sessionId,
    selectedAgentId: s.selectedAgentId,
    setSelectedAgentId: p.setSelectedAgentId,
    sessionIdRef: acp.sessionIdRef,
    chat: acp.chat,
    busy: acp.busy,
    ready: acp.ready,
    connecting: acp.connecting,
    loadingSession: acp.loadingSession,
    ensureAgent: acp.ensureAgent,
    startInboxSession: acp.startInboxSession,
    newChatInFocus: ws.newChatInFocus,
    startNewChat: acp.startNewChat,
    startSession: acp.startSession,
    resumeSession: acp.resumeSession,
    openSession: ws.openSession,
    splitRight: ws.splitRight,
    closePaneLeaf: ws.closePaneLeaf,
    beginPaneDrag: ws.beginPaneDrag,
    focusPane: ws.focusPane,
    onPaneRatio: ws.onPaneRatio,
    onExtraDraftChange: ws.onExtraDraftChange,
    onExtraAtBottom: ws.onExtraAtBottom,
    onExtraQueue: ws.onExtraQueue,
    mainPaneBusy: view.mainPaneBusy,
    review,
    reviewOpen: review.open,
    previewPath: review.preview.path,
    previewText: review.preview.text,
    previewTruncated: review.preview.truncated,
    previewError: review.preview.error,
    persist: p.persist,
    git: git.git,
    changes: git.changes,
    gitCommits: git.commits,
    gitBranchList: git.branches,
    gitWorktrees: git.worktrees,
    refreshGit: git.refresh,
    answerPermission: p.answerPermission,
    refreshInspect: p.refreshInspect,
    openHub: p.openHub,
    openReview: p.openReview,
    openPreview: review.openPreview,
    openMenu: ws.openMenu,
    beginEditTitle: ws.beginEditTitle,
    cancelEditTitle: ws.cancelEditTitle,
    commitTitle: ws.commitTitle,
    moveInboxToProject: ws.moveInboxToProject,
    restoreGenerated: ws.restoreGenerated,
    selectProject: ws.selectProject,
    addProject: ws.addProject,
    refreshInbox: ws.refreshInbox,
    switchWorkdir: ws.switchWorkdir,
    removeSession: ws.removeSession,
    applyMode: slash.applyMode,
    applySessionModel: slash.applySessionModel,
    applyModel: slash.applyModel,
    applyEffort: slash.applyEffort,
    effort: s.effort,
    runSlash: slash.runSlash,
    submitPrompt: acp.submitPrompt,
    altSubmit: acp.altSubmit,
    sendPrompt: acp.sendPrompt,
    cancelTurn: acp.cancelTurn,
    onDraftChange: acp.onDraftChange,
    newWorktreeSession: ws.newWorktreeSession,
    switchWorktree: ws.switchWorktree,
    checkoutBranch: gitActions.checkoutBranch,
    applyRewind: ws.applyRewind,
    toggleExpand: ws.toggleExpand,
    current: view.current,
    currentTitle: view.currentTitle,
    sessionPreviews: view.sessionPreviews,
    sessionModel: view.sessionModel,
    recapText: view.recapText,
    showRecap: view.showRecap,
    dismissRecap: p.dismissRecap,
    copyAllConversation: ws.copyAllConversation,
    cwdLocked: view.cwdLocked,
    menuSession: s.menu
      ? s.menu.kind === "row"
        ? ws.findSessionById(s.menu.id)
        : view.current
      : null,
    findSessionById: ws.findSessionById,
    usage: view.usage,
    plan: view.plan,
    userTurns: view.userTurns,
    urlChips: view.urlChips,
    openSettings: () => s.setSettingsOpen(true),
    allSessions: p.allSessions,
    palette,
    statusFor: view.statusFor,
    sidebarSections: view.sidebarSections,
    visibleHotkeySessions: view.visibleHotkeySessions,
    rewindForItem: p.rewindForItem,
    rewindPreview: view.rewindPreview,
    subagentCards: view.catalog,
    planComplete: view.planComplete,
    dashboardSessions: view.dashboardSessions,
    memoryPath: view.memoryPath,
    agentsMdPath: view.agentsMdPath,
    mainPermission: view.mainPermission,
    mainPermissionView: view.mainPermissionView,
    panePermissions: view.panePermissions,
    takeover: view.takeover,
    hero: view.hero,
    turnFiles: view.turnFiles,
    terminalTools: view.terminalTools,
    reviewTabs: view.reviewTabs,
    reconciledReviewTab: view.reconciledReviewTab,
    jobs: view.jobs,
    catalog: view.catalog,
    goal: view.goal,
    goalView: s.goalView,
    health: view.health,
    runStatus: view.runStatus,
    turnStats: view.turnStats,
    hasOpenSession: !!acp.sessionId,
    injectedSessions: acp.injectedSessions,
    dismissInjectedSession: acp.dismissInjectedSession,
    dreamDiary: dream.diary,
    dreamStatus: dream.status,
    dreamCorpus: dream.corpus,
    dreamUserMdPath: dream.userMdPath,
    onDreamNow: dream.onDreamNow,
    profileUpdated: dream.profileUpdated,
    dismissProfileUpdated: dream.dismissProfileUpdated,
  };
}
